-- Drop Table's
DROP TABLE IF EXISTS EMPRESA_CONSTRUCAO.REL_OBRA_MATERIAL;
DROP TABLE IF EXISTS EMPRESA_CONSTRUCAO.REL_ENCOMENDA_MATERIAL;
DROP TABLE IF EXISTS EMPRESA_CONSTRUCAO.ENCOMENDA;
DROP TABLE IF EXISTS EMPRESA_CONSTRUCAO.FORNECEDOR;
DROP TABLE IF EXISTS EMPRESA_CONSTRUCAO.MATERIAL_CONSTRUCAO;
DROP TABLE IF EXISTS EMPRESA_CONSTRUCAO.REL_OBRA_EMPREGADO;
DROP TABLE IF EXISTS EMPRESA_CONSTRUCAO.REL_OBRA_SERVICO;
DROP TABLE IF EXISTS EMPRESA_CONSTRUCAO.OBRA;
DROP TABLE IF EXISTS EMPRESA_CONSTRUCAO.CLIENTE;
DROP TABLE IF EXISTS EMPRESA_CONSTRUCAO.SERVICO;
DROP TABLE IF EXISTS EMPRESA_CONSTRUCAO.CEO;
DROP TABLE IF EXISTS EMPRESA_CONSTRUCAO.EMPREGADO;
DROP TABLE IF EXISTS EMPRESA_CONSTRUCAO.DEPARTAMENTO;


-- Drop Schema
DROP SCHEMA IF EXISTS EMPRESA_CONSTRUCAO;


-- Drop Function's (UDF's)
DROP FUNCTION IF EXISTS getDepartamentoById;

DROP FUNCTION IF EXISTS getEmpregadoByName;
DROP FUNCTION IF EXISTS getEmpregadoBySexBirthSalary;

DROP FUNCTION IF EXISTS getClientByName;

DROP FUNCTION IF EXISTS getObraByClientNif;
DROP FUNCTION IF EXISTS getObraByDate;

DROP FUNCTION IF EXISTS getObraServicoByObra;
DROP FUNCTION IF EXISTS getObraServicoByServico;

DROP FUNCTION IF EXISTS getObraEmpregadoByObra;
DROP FUNCTION IF EXISTS getObraEmpregadoByEmpregado;
DROP FUNCTION IF EXISTS getTotalHoursByEmpregado;
DROP FUNCTION IF EXISTS getTotalHoursAllEmployees;

DROP FUNCTION IF EXISTS getMaterialByCategory;
DROP FUNCTION IF EXISTS getMaterialByName;
DROP FUNCTION IF EXISTS getMaterialByQuantity;
DROP FUNCTION IF EXISTS getMateriaisByObra;
DROP FUNCTION IF EXISTS getMateriaisByEncomenda;

DROP FUNCTION IF EXISTS getFornecedorByName;

DROP FUNCTION IF EXISTS getEncomendaByDateFornIdObraId;
DROP FUNCTION IF EXISTS getTotalEncomendas;

DROP FUNCTION IF EXISTS getTablesInfo;


-- Drop Store Procedure's
DROP PROCEDURE IF EXISTS create_department;
DROP PROCEDURE IF EXISTS add_employee;
DROP PROCEDURE IF EXISTS create_obra;
DROP PROCEDURE IF EXISTS create_client;
DROP PROCEDURE IF EXISTS add_constr_material;
DROP PROCEDURE IF EXISTS create_fornecedor;
DROP PROCEDURE IF EXISTS add_encomenda;
DROP PROCEDURE IF EXISTS add_material_enc;
DROP PROCEDURE IF EXISTS add_empregado_obra;
DROP PROCEDURE IF EXISTS add_service_obra;

DROP PROCEDURE IF EXISTS update_department;
DROP PROCEDURE IF EXISTS update_employee;
DROP PROCEDURE IF EXISTS update_client;
DROP PROCEDURE IF EXISTS update_obra;
DROP PROCEDURE IF EXISTS update_fornecedor;
DROP PROCEDURE IF EXISTS update_mat_constr

DROP PROCEDURE IF EXISTS delete_department;
DROP PROCEDURE IF EXISTS delete_employee;
DROP PROCEDURE IF EXISTS delete_obra;
DROP PROCEDURE IF EXISTS delete_client;
DROP PROCEDURE IF EXISTS delete_fornecedor;
DROP PROCEDURE IF EXISTS delete_material_enc;
DROP PROCEDURE IF EXISTS delete_mat_constr;


-- Drop trigger's
DROP TRIGGER IF EXISTS work_day_check;
DROP TRIGGER IF EXISTS salary_check;


-- Drop indexes
DROP INDEX IF EXISTS idxEmpName ON EMPRESA_CONSTRUCAO.EMPREGADO;
DROP INDEX IF EXISTS idxClientName ON EMPRESA_CONSTRUCAO.CLIENTE;

