DROP TABLE IF EXISTS PRESCRICAO.PRESC_FARMACO;
DROP TABLE IF EXISTS PRESCRICAO.PRESCRICAO;
DROP TABLE IF EXISTS PRESCRICAO.FARMACO;
DROP TABLE IF EXISTS PRESCRICAO.FARMACEUTICA;
DROP TABLE IF EXISTS PRESCRICAO.FARMACIA;
DROP TABLE IF EXISTS PRESCRICAO.PACIENTE;
DROP TABLE IF EXISTS PRESCRICAO.MEDICO;
DROP SCHEMA IF EXISTS PRESCRICAO;
GO

CREATE SCHEMA PRESCRICAO;
GO

CREATE TABLE PRESCRICAO.MEDICO (
    numSNS          INT             PRIMARY KEY,
    nome            VARCHAR(50)     NOT NULL,
    especialidade   VARCHAR(30)     NOT NULL
)

CREATE TABLE PRESCRICAO.PACIENTE (
    numUtente       INT             PRIMARY KEY,
    nome            VARCHAR(50)     NOT NULL,
    dataNasc        DATE            NOT NULL,
    endereco        VARCHAR(100)
)

CREATE TABLE PRESCRICAO.FARMACIA (
    nome            VARCHAR(50)     PRIMARY KEY,
    telefone        INT             NOT NULL,
    endereco        VARCHAR(100)    NOT NULL
)

CREATE TABLE PRESCRICAO.FARMACEUTICA (
    numReg          INT             PRIMARY KEY,
    nome            VARCHAR(50)     NOT NULL,
    endereco        VARCHAR(100)    NOT NULL
)

CREATE TABLE PRESCRICAO.FARMACO (
    numRegFarm      INT,
    nome            VARCHAR(50),
    formula         VARCHAR(20)     NOT NULL,

    PRIMARY KEY (numRegFarm, nome)
)

CREATE TABLE PRESCRICAO.PRESCRICAO (
    numPresc        INT             PRIMARY KEY,
    numUtente       INT             NOT NULL,
    numMedico       INT             NOT NULL,
    farmacia        VARCHAR(50),
    dataProc        DATE,

    FOREIGN KEY (numUtente) REFERENCES PRESCRICAO.PACIENTE (numUtente) ON UPDATE CASCADE,
    FOREIGN KEY (numMedico) REFERENCES PRESCRICAO.MEDICO (numSNS) ON UPDATE CASCADE,
    FOREIGN KEY (farmacia) REFERENCES PRESCRICAO.FARMACIA (nome) ON UPDATE CASCADE
)

CREATE TABLE PRESCRICAO.PRESC_FARMACO (
    numPresc        INT,
    numRegFarm      INT,
    nomeFarmaco     VARCHAR(50)

    PRIMARY KEY (numPresc, numRegFarm, nomeFarmaco),
    FOREIGN KEY (numPresc) REFERENCES PRESCRICAO.PRESCRICAO (numPresc) ON UPDATE CASCADE,
    FOREIGN KEY (numRegFarm) REFERENCES PRESCRICAO.FARMACEUTICA (numReg) ON UPDATE CASCADE,
    FOREIGN KEY (numRegFarm, nomeFarmaco) REFERENCES PRESCRICAO.FARMACO (numRegFarm, nome) ON UPDATE CASCADE
)
