name: Evaluation

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        timeout-minutes: 2
        run: |
          pytest -vv --timeout=20
