name: Evaluation 

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  unit_tests:
    # Name the Job
    name: Unit Tests
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Launch server into background
        run: |
          python3 server.py & > /dev/null ; PID=$!; sleep 1; ps -p $PID > /dev/null

      - name: Test with pytest
        timeout-minutes: 1
        run: |
          pytest
  
