-- Exercise 4.1.4

DROP TABLE IF EXISTS PHARMACY_MANAGEMENT.REL_DRUG_PHARMACY;
DROP TABLE IF EXISTS PHARMACY_MANAGEMENT.REL_DRUG_PHARMACEUTICAL;
DROP TABLE IF EXISTS PHARMACY_MANAGEMENT.PHARMACEUTICAL;
DROP TABLE IF EXISTS PHARMACY_MANAGEMENT.REL_PRESCRIPTION_DRUG;
DROP TABLE IF EXISTS PHARMACY_MANAGEMENT.DRUG;
DROP TABLE IF EXISTS PHARMACY_MANAGEMENT.PRESCRIPTION;
DROP TABLE IF EXISTS PHARMACY_MANAGEMENT.PHARMACY;
DROP TABLE IF EXISTS PHARMACY_MANAGEMENT.PATIENT;
DROP TABLE IF EXISTS PHARMACY_MANAGEMENT.DOCTOR;
DROP SCHEMA IF EXISTS PHARMACY_MANAGEMENT;
GO

CREATE SCHEMA PHARMACY_MANAGEMENT;
GO

CREATE TABLE PHARMACY_MANAGEMENT.DOCTOR (
    number              INT             NOT NULL        PRIMARY KEY,
    name                VARCHAR(30)     NOT NULL,
    specialty           VARCHAR(100)    NOT NULL,
);

CREATE TABLE PHARMACY_MANAGEMENT.PATIENT (
    number              INT             NOT NULL        PRIMARY KEY,
    name                VARCHAR(30)     NOT NULL,
    birth_date          DATE            NOT NULL,
    address             VARCHAR(50)     NOT NULL,
);

CREATE TABLE PHARMACY_MANAGEMENT.PHARMACY (
    nif                 INT             NOT NULL        PRIMARY KEY,
    name                VARCHAR(30)     NOT NULL,
    phone_number        INT             NOT NULL,
    address             VARCHAR(50)     NOT NULL,
);

CREATE TABLE PHARMACY_MANAGEMENT.PRESCRIPTION (
    number              INT             NOT NULL        PRIMARY KEY,
    creation_date       DATE            NOT NULL,
    dispatch_date       DATE            NOT NULL,
    DOCTOR_number       INT             NOT NULL,
    PATIENT_number      INT             NOT NULL,
    PHARMACY_nif        INT             NOT NULL,

    FOREIGN KEY (DOCTOR_number) REFERENCES PHARMACY_MANAGEMENT.DOCTOR(number),
    FOREIGN KEY (PATIENT_number) REFERENCES PHARMACY_MANAGEMENT.PATIENT(number),
    FOREIGN KEY (PHARMACY_nif) REFERENCES PHARMACY_MANAGEMENT.PHARMACY(nif),
    CHECK (creation_date < dispatch_date),
);

CREATE TABLE PHARMACY_MANAGEMENT.DRUG (
    formula             VARCHAR(100)    NOT NULL        PRIMARY KEY,
);

CREATE TABLE PHARMACY_MANAGEMENT.REL_PRESCRIPTION_DRUG (
    PRESCRIPTION_number INT             NOT NULL,
    DRUG_formula        VARCHAR(100)    NOT NULL,

    PRIMARY KEY (PRESCRIPTION_number, DRUG_formula),
    FOREIGN KEY (PRESCRIPTION_number) REFERENCES PHARMACY_MANAGEMENT.PRESCRIPTION(number),
    FOREIGN KEY (DRUG_formula) REFERENCES PHARMACY_MANAGEMENT.DRUG(formula),
);

CREATE TABLE PHARMACY_MANAGEMENT.PHARMACEUTICAL (
    register_number     INT             NOT NULL        PRIMARY KEY,
    name                VARCHAR(30)     NOT NULL,
    phone_number        INT             NOT NULL,
    address             VARCHAR(50)     NOT NULL,
);

CREATE TABLE PHARMACY_MANAGEMENT.REL_DRUG_PHARMACEUTICAL (
    PHAR_reg_number     INT             NOT NULL,
    DRUG_formula        VARCHAR(100)    NOT NULL,

    PRIMARY KEY (PHAR_reg_number, DRUG_formula),
    FOREIGN KEY (PHAR_reg_number) REFERENCES PHARMACY_MANAGEMENT.PHARMACEUTICAL(register_number),
    FOREIGN KEY (DRUG_formula) REFERENCES PHARMACY_MANAGEMENT.DRUG(formula),
);

CREATE TABLE PHARMACY_MANAGEMENT.REL_DRUG_PHARMACY (
    DRUG_formula        VARCHAR(100)    NOT NULL,
    PHARMACY_nif        INT             NOT NULL,

    PRIMARY KEY (DRUG_formula, PHARMACY_nif),
    FOREIGN KEY (DRUG_formula) REFERENCES PHARMACY_MANAGEMENT.DRUG(formula),
    FOREIGN KEY (PHARMACY_nif) REFERENCES PHARMACY_MANAGEMENT.PHARMACY(nif),
);

