#
# (C) Tomás Oliveira e Silva, AED, November 2022
#
# makefile to compile all programs for the AED P.06 computer lab class
#

clean:
	rm -fv a.out
	rm -fv binary_search_tests

binary_search_tests:	binary_search_tests.c
	cc -Wall -O2 binary_search_tests.c -o binary_search_tests
